apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app001
  namespace: mayur-ns
  labels:
    app: nginx-app001
    env: test
    version: v1.0.0
spec:
  selector: 
    matchLabels: 
      app: nginx-app001
      env: test    
  template: 
    metadata: 
      labels:
        app: nginx-app001
        env: test
        version: v1.0.0
    spec:
      containers:
      - name: nginx-app001
        image: nginx:latest
        ports:
        - containerPort: 8080