apiVersion: apps/v1
kind: Deployment
metadata:
  name: mg-electronics
  namespace: mayur-ns
  labels:
    app: mg-electronics
    env: test
    version: v1.0.0
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector: 
    matchLabels: 
      app: mg-electronics
      env: test    
  template: 
    metadata: 
      labels:
        app: mg-electronics
        env: test
        version: v1.0.0
    spec:
      containers:
      - name: mg-electronics
        image: mayurghule/javapp:latest
        ports:
        - containerPort: 8080