# replicaset.yml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mg-electronics-rs
  namespace: mayur-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mg-electronics
  template:
    metadata:
      labels:
        app: mg-electronics
    spec:
      containers:
      - name: mg-electronics
        image: mayurghule/javapp:latest
        ports:
        - containerPort: 8080
