apiVersion: v1
kind: Service
metadata:
  name: nginx-app001
  namespace: mayur-ns
  labels:
    app: nginx-app001
    env: test
    version: v1.0.0
spec:
  selector:
      app: nginx-app001
      env: test
      version: v1.0.0
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort    
