apiVersion: v1
kind: Service
metadata:
  name: mg-electronics
  namespace: mayur-ns
  labels:
    app: mg-electronics
    env: test
    version: v1.0.0
spec:
  selector:
      app: mg-electronics
      env: test
      version: v1.0.0
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort    
